// try catch es10
// manejo de errores
try{
    hello();
}catch (error){
    console.log(error);
}


try{
    anotherFunction();
}catch {
    console.log("Esto es un error");
}